apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarr
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: bjw-s-labs.github.io/helm-charts
      chart: app-template
      targetRevision: 5.0.1
      helm:
        valueFiles:
          - $github/sonarr/values.yaml

    - repoURL: git@github.com:0x746172656b/homelab.git
      targetRevision: main
      ref: github

    - repoURL: git@github.com:0x746172656b/homelab.git
      targetRevision: main
      path: sonarr
  destination:
    server: https://kubernetes.default.svc
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
