services:
  qbittorrentvpn:
    image: binhex/arch-qbittorrentvpn:5.2
    container_name: qbittorrentvpn
    cap_add:
      - NET_ADMIN
    ports:
      - "8080:8080"
      - "8118:8118"
      - "9118:9118"
      - "58946:58946"
      - "58946:58946/udp"
    environment:
      - VPN_ENABLED=yes
      - VPN_USER=${VPN_USER}
      - VPN_PASS=${VPN_PASS}
      - VPN_PROV=${VPN_PROV}
      - VPN_CLIENT=openvpn
      - ENABLE_STARTUP_SCRIPTS=no
      - ENABLE_PRIVOXY=no
      - STRICT_PORT_FORWARD=yes
      - USERSPACE_WIREGUARD=no
      - ENABLE_SOCKS=no
      - LAN_NETWORK=10.10.93.0/24,192.168.2.0/24
      - NAME_SERVERS=1.1.1.1,1.0.0.1
      - DEBUG=false
      - WEBUI_PORT=8080
      - UMASK=000
      - PUID=0
      - PGID=0
    volumes:
      - /volume1/Jellyfin/:/data
      - /volume2/docker/qbittorrent-prod/config:/config
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
