---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCza3Z8Dm35iWicytpcFIrk84iwp8DyKlmfUdCanBVWcxEvy4pWk+7YAPOOzucTdrgkTGqcXIEUbeE3dfSPnm0waPDX0pSDtStjJfD5LQRe5fBYahbcMSdnSNdZmucW9tXnASSVQMItwJORpcT02/H4a1ugBRwp/wtGdwuslKXHxr6FnOymg3DZmmM6Re0HMQQaXYXim/yDhdjKgNQkx6tTnE4lC/SAikBbylPAOaWTj4QR1+FS2Sl7XOT5jiOaEhaFXcZSNQLqpNP57K+NklnTiZw3RwcuK8iAh1D0obeaMbtB1Tcnh7Ha+vAM/LSVxvHxmvzjSo6QaerleKE1YLxuSvOqzAYdA6Jmxl+iUQCFov04zwJ3y3pPyrwg5TtNIdU2hnrI8DvaXrBA2WsP+9xN4I1WEEBmni309lnA3MgrL0DGGdFq1b24guIUOWZFZbG8p366MiSYp7x+fbpzHJrXTK/hiM4zwhfU23Z+sDBnEWa9JCzsmnDb7LSzvjJ9oOa/RInCGdMDgpNCdSmwkqIvIMvVrduVfdK04dJjjz72Sj/SKZ5ypOY558Bz3V+hjPkuvM4hVvx869YQ57wZYFoDAKvQXewnGToA1HFHkAem6LFwM1XFZBkBiMJg7f8EWmrSL5fJrE+0FaDsYEV5UlNfyQA7CBqrITthEegK5vh7NpTtqC0C39IVzFL0mp+D78YQpiv98HKdSQGrgH+t9Chyw+b5rd+r1f7ZOzg9EcalQWYOEIyCwPcc
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
