---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-secrets
  namespace: authentik
spec:
  encryptedData:
    postgresql_password: AgBFYaM74FGplMWjSn0kHe2V3Q8XGGk3KfPpmgspWpD3FvySdyLz4nUluCuRs1QmB6GwfyRmStYhE1lPZCZXeWsU4AvZw1FhvJTJZN3QkWDKCUP3upXGYpagET/VeqTsf2jvkDcdrCIigQZYnabDybfMcoaoZ7GM+1ROyTEI6phBZN8Ea4KnnjPuRIEyGzALk57i2APa13uErD7S1uil/AuG+ALCWGgw1XScO2LADWos4WF4YDr6J9htnZGtpotFFhVirD0HNsB7SIbex9WnnbnMag9UKq4X0oh87oLdaD9T0lMGWRjMazPFwI9ur+KOp7SqxKu2XrIYWP7WCmEXifWZ8V4NlmPhWEL3GFS3z5jUqXC1trqDkisT1l4U+S7BXeCkJYDcKcVNnifoKoB82ubXGByAlXvyI9dupHrhkLLHQSjjpFJ9tHdNgGlvABAyqu1paVgiCJeUcMjokZpgFlpaNyj5q4nCzK7IClkI6sKYxd7xorgfNqDWLStDurchZsbyEtcXE5PszJdD0tOEMmefavp/BJyxQj3E74PdH5rClqpzOMZRBaYd75ZetB2VIh9E2JCAj2AXAPV1qPvKOnUb/byjBZQqdruULYYxebKOywJClkQ2dBOdLuLTJZr1wB7G+Ot8hqtjM3uqhg0PQtVu904a1OHUUUnNKbjeK2NPIg8ht7K4rjqYH5pi6/ClmslDMfTlyy1/KmgDyY7UhhjcmcxDwZ+DmzSBmXJW8KpCk4OnbyVBMoIozPkpZXmIprvvFKaW26aF3p8VjcF+8QmM
    secret_key: AgCk82BRcD7xGbembF9rlAi2f0xU8d1Xdt9o7VylrBkQ/3qu/vPdpfhjDCnPjHRUMUXUiDXTODWsZEBj9P43BNyBTg/2wHFqEfHewe/ApXa5Ne8vU3klw8BRLVSHgZcC37W9krC7E3HDdSTJDJX1uIm103b9OlA044jlkt4mtVXFP4xC93uBLjvXFzfclZkkWU6b9zhs4TMEYmkJXvdS+uWXyxKjYnG9CSROK8KI18+tUIiwE9t6StbQnV8l78NEtjyyhJuiUctmMW8gM8zajWDMACIQNvVRjBXCZdC7qJpQ3YsAJmULs39/qGtqbOSQTxcHxvfprSqkfRUa5i6YYbnDmbQIG8wf2LJm2kx/Xf3atR2gic4HvU+0fbeikeFznCJEaXtCmrRdxGyFpNxi7f05PjJpQ4cZhfTycSwszt3+NzzJyIuEUiMvMLSCytkbpuSHpp22hu1AUjL02PsBfsy/Qr03mFdz/a9pA9hRoNpfYbMJotufapBs/DmzPB47awMb60KNrriE0CPS057jw7ry+G4Jj/b2D1pan0D0e5tnYresk0F/VnMagC05InGuDL1m62ZFj9mEwCSKzNWY4EWhp87hCX2HhBAhHfmYJj2CjRRLOXsijTi1Tw+zivWAZc+A1bHHwpj51Q5bM3mzjeomHf8RRSsCCPcCljaRx81r/v0/Q0xaeK2MGWhdZ8Q0ZOK0DrKuVOrb/+Nep8PSV1lx/j680O+Iqmkdzw6soXcuLb1idAxKKBgEh4bFiuZCZC94ausN1byBy4JwDTTnicapKdQMSsg0GH+a1sSW357M6g==
  template:
    metadata:
      name: authentik-secrets
      namespace: authentik
    type: Opaque
