apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: pve-exporter
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  metricsPath: /pve
  params:
    module:
      - default
  staticConfigs:
    - targets:
        - "10.10.93.101"
  relabelings:
    - sourceLabels: [__address__]
      targetLabel: __param_target
    - sourceLabels: [__param_target]
      targetLabel: instance
    - targetLabel: __address__
      replacement: "10.10.93.101:9221"
