apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nginx-ingress-route
  namespace: nginx
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`nginx.local.khider.fr`) 
      services:
        - name: nginx-server
          port: 80
  tls:
    secretName: nginx-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx.local.khider.fr-cert
  namespace: nginx
spec:
  secretName: nginx-cert
  issuerRef:
    name: cloudflare-issuer
    kind: ClusterIssuer
  dnsNames:
    - nginx.local.khider.fr
    - nginx.khider.fr
