apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prowlarr.local.khider.fr-cert
  namespace: media
spec:
  secretName: prowlarr-cert
  issuerRef:
    name: cloudflare-issuer
    kind: ClusterIssuer
  dnsNames:
    - prowlarr.local.khider.fr
    - prowlarr.khider.fr
