apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prowlarr-ingress-route
  namespace: media
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`prowlarr.local.khider.fr`)
      services:
        - name: prowlarr
          port: 9696
      middlewares:
        - name: prowlarr-middleware
        - namespace: traefik
  tls:
    secretName: prowlarr-cert
