services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:2.15.1'
    restart: unless-stopped
    ports:
      - '81:81'
      - '10.10.93.135:80:80'
      - '44301:443'
    volumes:
      - ./deployment/data:/data
      - ./deployment/letsencrypt:/etc/letsencrypt
