# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/library/common/values.schema.json

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
  labels:
    pod-security.kubernetes.io/enforce: privileged
spec:
  interval: 10m
  chart:
    spec:
      chart: app-template
      version: 5.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system

  valuesFrom:
    - kind: Secret
      name: qbittorrent-vpn-secret
      valuesKey: wg_private_key
      targetPath: controllers.qbittorrent.initContainers.vpn.env[2].value
    - kind: Secret
      name: qbittorrent-vpn-secret
      valuesKey: wg_address
      targetPath: controllers.qbittorrent.initContainers.vpn.env[3].value

  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1001
        runAsNonRoot: true
        runAsUser: 1001
        seccompProfile:
          type: RuntimeDefault

    controllers:
      qbittorrent:
        annotations:
          secret.reloader.stakater.com/reload: qbittorrent-vpn-secret

        initContainers:
          vpn:
            image:
              repository: qmcgaw/gluetun
              tag: v3.41.1
              pullPolicy: IfNotPresent
            restartPolicy: Always
            env:
              - name: VPN_SERVICE_PROVIDER
                value: surfshark
              - name: VPN_TYPE
                value: wireguard
              - name: WIREGUARD_PRIVATE_KEY
                value: "${surfshark_wg_private_key}"
              - name: WIREGUARD_ADDRESSES
                value: "${surfshark_wg_address}"
              - name: SERVER_COUNTRIES
                value: France
              - name: FIREWALL_INPUT_PORTS
                value: "80"
              - name: WIREGUARD_IMPLEMENTATION
                value: boringtun
              - name: DOT
                value: "off"
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
              readOnlyRootFilesystem: true
              runAsNonRoot: true
              runAsUser: 1001
              runAsGroup: 1001
              volumeMounts:
                - name: tmp
                  mountPath: /run

        containers:
          app:
            image:
              repository: ghcr.io/home-operations/qbittorrent
              tag: 5.2.1@sha256:8d58d9ad18a1fb5e556e68bde7ac06046847cc97069257f01d2e1ec0d27ff019
            env:
              TZ: Europe/Paris
              QBT_WEBUI_PORT: &port 80
              QBT_TORRENTING_PORT: &torrentPort 50413
            resources:
              requests:
                cpu: 10m
                memory: 250Mi
                ephemeral-storage: 5Gi
              limits:
                memory: 2Gi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"] }
              readOnlyRootFilesystem: true

    persistence:
      config:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 1Gi

      media:
        type: nfs
        server: nas.local.khider.fr
        path: /volume1/Jellyfin
        globalMounts:
          - path: /media
      tmp:
        type: emptyDir
        sizeLimit: 1Gi

    service:
      main:
        controller: qbittorrent
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: false
