---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: qbittorrent-vpn-secret
  namespace: media
spec:
  encryptedData:
    wg_address: AgC3N2KSnWnIKQM3sxePPUYDo8ebHt1PwzQvvzOlpf47OO5xvPVUwIwcrPS/JFoCTRqC5M9rm9KtFPmd+yuhSWXS6Wwm4/YNNl6yL1CanvzCSYlWcx8YM5UbQamDHKOXvOOAIHzfR4qMiFXRu0yRw3ZIpA1nyLoZxlnf4lp31jN3BwmhDLC9ykDV3KrGxfzsVRvF0HQS5WpF5Fnta0yzfpLv0a56vi+Aqx7Cl10cxapEpq0hu4btcfsJ+SaVtXDYnf4pArI3e6w7sGegX7dBNCpoUGeNGEW3CJgHysBGSxcoMg+PApG3c8WN3vWJ1eg1M7/n7Gkprnhyrz7so9he3P29Z5+floLE4kELxhNiNNX9VvOppaiVNupMI/XeKh1fmmf9odNw6+ZGSGHY7t7kFZJgaVSwuHAgWvFnQOoCXf5qgx2yU76b54zV87lpfLbdTNy6+iVC17UFK/BRPFdJu9oyKWrEcWW9TKDsyLJ6UTEAo7RTpPKnXUtYMY80q+FKKxBRixLqAMtpBPdC5e3btzoKQ/KLOeLP3Gn+UlLbYyDhRaeoZYdkLQWqmMNyE8aGQu3ZvRmqLEfrylvHWwr+59+BzKfuvfyVFFdIPrSfTu5Q3ZClEw4gDSNUK4m/gdLNUI6kHORV1P+KU301WyjTC5P9Nsi3F+isRP4zzsWXcCb4aiwv9lx02ZFVQaEDFc79BwJPoix/pOftfSohjwY=
    wg_private_key: AgC38vW+15VK7VrNaGDvrBCfJZ19Lo/ocmuYPxQJwOQ94aa14upC/CzPVSRKA4IY+oE1WFb/qm2Oo5dUSFPnK4RA5ZOkrYKwEFltwrGx0jcu4CWImuHyyTh1ZD9KSe1ZeDq+17kZottKmsybstlVZ3tMqk5Af3hkd4xA8M2rfal8Y/oGekbZbH8Xa2J2eFPMtTHOWXSuQ9B+s+hmaAI4KOaWo2so8/KLehatc9DiYK3hjibol2bjA4CDCHDgquK5mLmHQRj5Rn1k+GrOjVOYzbGvRO2NinvPgomI1IXHIu2/XbBdlS64Q/bsCbUPW+CYw/abgaBF4POqAIModS/4di7B9H5pmaV9FKYFkm8gguiONZLt66p1Uhg7V4CoIeb78QBcgE32234OENDc0Si8zAMVpL+btyvt7+UGnziJcmQk+OLz0PVnW31Y91P+NVDYYNPeX6HC7Spv31h4VlNdZs4bUbzy08Qumlj3Ddyk4Q/85zHEUL8jNY/27eNZOkmjU1ol/HsYetJk8gROssY5KIz2z8QfjFRCG1JpcoN/At2chb38IphteTJXt7NaeltgT60w3Zk5p9bANM/NGPduEbPlF+flQAv0VYeOa5Kfc+SU13UkLIV/2ydW/cZA03EBhzYE/9/kFYXvz2f2/UrdWPrDVfnmrsNyKve5i6BSmyGa8Eoi9Xoyb6uhQuoWdCr9NH0RBp5lj3CzW4bxgdY7PQ2eWdt2Qp/Bgt0HeOSMk71p9/E2gxFYGEMnwwPyxw==
  template:
    metadata:
      name: qbittorrent-vpn-secret
      namespace: media
    type: Opaque
