services:
  gitlab:
    image: gitlab/gitlab-ce:19.1.0-ce.0

    container_name: gitlab
    restart: unless-stopped
    hostname: 'gitlab.local.khider.fr'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.local.khider.fr/'
        letsencrypt['enable'] = false
        nginx['redirect_http_to_https'] = true
        nginx['ssl_certificate'] = "/etc/gitlab/ssl/fullchain.cer"
        nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/gitlab.local.khider.fr.key"
    ports:
      - '10.10.93.145:80:80'
      - '10.10.93.145:443:443'
      - '10.10.93.145:22:22'
    volumes:
      - './config:/etc/gitlab'
      - './logs:/var/log/gitlab'
      - './data:/var/opt/gitlab'
      - '/home/tarek/.acme.sh/gitlab.local.khider.fr_ecc:/etc/gitlab/ssl:ro'
    shm_size: '256m'

volumes:
  gitlab-ssl:
    external: true
