apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - source.yaml
  - sonarr-release.yaml
  - sonarr-ingress.yaml

configMapGenerator:
  - name: sonarr-values
    files:
      - values.yaml=values.yaml
