apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sonarr-deployment
  namespace: flux-system
spec:
  interval: 10m
  path: ./sonarr
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
